### ISSUE TITLE
How to export?

### ISSUE THREAD

**Issue by NickHodges** [oliverbenns/joy-theme-creator#1]
Hey!  This is a great project, and I'm interested in using it. 

The README says:

"It also provides the ability for you to copy the theme configuration object directly into your own Joy UI project's source code after tinkering with these controls."

But I see no way to do that.  Am I missing something obvious?

**Comment by NickHodges** [comment]
Oh wait, never mind.  I got it.

If anyone sees this, the config tab will contain an object you can use as you change settings.

**Comment by NickHodges** [comment]
Closed

**Comment by oliverbenns** [comment]
Thanks for providing the solution here. If this continues to come up I'll see about how to make this more obvious.
